# Site settings
author: Ryan Evans
title: Full Stack Web Development ~ Software Engineering
header-img: img/home-bg.png
email: ryanwevans@icloud.com
copyright_name: Ryan Evans
description: > # this means to ignore newlines until "baseurl:"
  Sharing my knowledge learned from Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ryanwevans

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
